### ISSUE TITLE
Can you shared the paper?

### ISSUE THREAD

**Issue by MirrorYu** [zju3dv/RLP_VIO#1]
I have no acess to the paper download url, can you sent it to me by email?
My email: 2458006366@qq.com
Thanks a lot!

**Comment by MirrorYu** [comment]
@ZibYang

**Comment by zion-ziyang** [comment]
You can view the paper online from this URL: https://onlinelibrary.wiley.com/doi/epdf/10.1002/cav.2046
Also, I sent a copy to you, and please check. Thank you for your interest in our work

**Comment by MirrorYu** [comment]
Thanks a lot！
